services:
  solution:
    image: ${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BUILD_IMAGE: ${BUILD_IMAGE}
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
  traefik:
    volumes:
      - ./docker/traefik:C:/etc/traefik
  mssql:
    image: ${COMPOSE_PROJECT_NAME}-xp0-mssql:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/mssql
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}nonproduction/mssql-developer:2017-${SITECORE_VERSION}
    mem_limit: ${MEM_LIMIT_SQL}
    volumes:
      - type: bind
        source: ${LOCAL_DATA_PATH}\mssql
        target: c:\data
  solr:
    image: ${COMPOSE_PROJECT_NAME}-xp0-solr:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/solr
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}nonproduction/solr:8.8.2-${SITECORE_VERSION}
    volumes:
      - type: bind
        source: ${LOCAL_DATA_PATH}\solr
        target: c:\data
  solr-init:
    image: ${COMPOSE_PROJECT_NAME}-xp0-solr-init:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/solr-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-solr-init:${SITECORE_VERSION}
    mem_limit: ${MEM_LIMIT_SOLR}
  id:
    image: ${COMPOSE_PROJECT_NAME}-xp0-id:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-id6:${SITECORE_VERSION}
  cm:
    image: ${COMPOSE_PROJECT_NAME}-xp0-cm:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}sitecore-docker-tools-assets:${TOOLS_VERSION}
        SOLUTION_IMAGE: ${COMPOSE_PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    volumes:
      - ${LOCAL_DEPLOY_PATH}\website:C:\deploy
      - ${LOCAL_DATA_PATH}\logs:C:\inetpub\wwwroot\App_Data\logs
    #entrypoint: powershell -Command "& C:/\tools/\entrypoints/\iis/\Development.ps1"
  xconnect:
    image: ${COMPOSE_PROJECT_NAME}-xp0-xconnect:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/xconnect
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xconnect:${SITECORE_VERSION}
  xdbsearchworker:
    image: ${COMPOSE_PROJECT_NAME}-xp0-xdbsearchworker:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/xdbsearchworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbsearchworker:${SITECORE_VERSION}
  xdbautomationworker:
    image: ${COMPOSE_PROJECT_NAME}-xp0-xdbautomationworker:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/xdbautomationworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbautomationworker:${SITECORE_VERSION}
  cortexprocessingworker:
    image: ${COMPOSE_PROJECT_NAME}-xp0-cortexprocessingworker:${VERSION:-latest}
    build:
      context: ${LOCAL_BUILD_PATH}/cortexprocessingworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cortexprocessingworker:${SITECORE_VERSION}